name: Build macOS App

on:
  push:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Python environment and install dependencies
        run: |
          python3 -m venv venv
          ./venv/bin/pip install --upgrade pip
          ./venv/bin/pip install -r requirements.txt
	  ./venv/bin/pip install pyinstaller

      - name: Build the app using PyInstaller
        run: |
          ./venv/bin/pyinstaller --windowed --onefile main_app.py \
            --icon=app_icon.ico \
            --add-data "UK_Logo_white.png:." \
            --add-data "AW_logo.png:." \
            --add-data "generate_srt.py:." \
            --add-data "punctuation_replacer.py:." \
            --add-data "transcriber.py:." \
            --collect-all whisper

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macOS-app
          path: dist/
